- name: Full EC2 + Docker workflow
  hosts: localhost
  gather_facts: no
  vars:
    aws_region: us-east-1
    instance_type: t2.micro
    ami: ami-0c94855ba95c71c99    # Ubuntu 22.04, поменяй на свой регион
    key_name: my_aws_key          # SSH ключ для инстанса
    security_group: default
    docker_image: nginx:latest

  tasks:

    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: ansible-test
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami }}"
        region: "{{ aws_region }}"
        security_groups: ["{{ security_group }}"]
        wait: yes
      register: ec2

    - name: Wait for SSH to come up
      ansible.builtin.wait_for:
        host: "{{ ec2.instances[0].public_ip_address }}"
        port: 22
        delay: 10
        timeout: 300
        state: started

    - name: Add new EC2 instance to dynamic inventory
      add_host:
        name: "{{ ec2.instances[0].public_ip_address }}"
        groups: launched
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/my_aws_key

- name: Install Docker and run container
  hosts: launched
  become: yes
  gather_facts: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Run Docker container
      community.docker.docker_container:
        name: web
        image: "{{ docker_image }}"
        state: started
        ports:
          - "80:80"

- name: Terminate EC2 instance
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Terminate the instance
      amazon.aws.ec2_instance:
        instance_ids: "{{ ec2.instances[0].id }}"
        region: "{{ aws_region }}"
        state: absent