- name: Install docker on remote servers
  hosts: remote_servers
  become: yes
  tasks:
    - name: Update packages
      apt:
        update_cache: yes
    
    - name: Install docker
      apt:
        name: docker.io
        state: present

    - name: Enable and start docker service
      systemd:
        name: docker
        enabled: yes
        state: started